### ISSUE TITLE
issue after upgrade to 1.0.4

### ISSUE THREAD

**Issue by minhl** [Vanderhoof/PyDBML#25]
Environment:
Windows10
Python 3.9.5
pydbml 1.0.4
import pydbml
AttributeError: type object 'ParserElement' has no attribute 'set_default_whitespace_chars'
uninstall 1.0.4 and reinstall 0.4.2 resolved issue.

**Comment by minhl** [comment]
pyparsing  2.4.7

**Comment by Vanderhoof** [comment]
This should be fixed by

```
pip install pyparsing --upgrade
```

I'll update the version limit in `setup.py` so that problem won't arise after PyDBML install

**Comment by minhl** [comment]
upgrade pyparsing to 3.0.9 fixed the issue. Thanks.
